# Generated by Django 5.0.1 on 2024-01-16 19:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('firt_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=20)),
                ('department_id', models.UUIDField(blank=True, null=True)),
                ('manager_id', models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
