# Generated by Django 5.0.1 on 2024-01-16 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='firt_name',
            new_name='first_name',
        ),
    ]
