# Generated by Django 5.0.1 on 2024-01-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_department_id_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
